### ISSUE TITLE
About our recent task list

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#178]
TODO Task
- [x]  Project Architecture Improvements. [issue #177 ] 
  - [x] Full support for Flink serialization and deserialization mechanisms.
  - [x] No more use Row Source, Sink to implementations the Table&SQL API.
  - [x] Add test cases to cover SQL
- [ ] Parallel Tasks: merging ways of communicating with the flink community  [issue #225 ]
- [x] Message Metadata Processing. [issue #179 ] 
   - [x] Complete the development of this feature
   - [x] add test cases to cover metadata.
- [x] New api key shared support. [issue #166] 
   - [x] add test cases to cover key-shared mode
   - [x] add example for this feature.
- [ ] Batch streaming all-in-one. [issue #187 ]
- [x] Schema compatibility check.
- [x] Flink Version Support Program [issue #181 ] 
- [x] Support upsert source [issue #184]
- [x] New watermarker implementation
- [ ] Support New SInk API [issue #224 ]
